### ISSUE TITLE
App Transport Security policy

### ISSUE THREAD

**Issue by vandenbrakel** [PhilipsHue/PhilipsHueSDK-iOS-OSX#101]
Xcode 7 made App Transport Security policy default. This means secure connections are required even on local IP's. This results in the SDK not being able to connect to the bridge when compiled in xcode7 (iOS9 and above).
For the moment you should ATS via the NSAllowsArbitraryLoads key. 

Read: https://forums.developer.apple.com/thread/6205

**Comment by BramV** [comment]
I encountered the same problem and I've change the plist file in #105 to allow unsafe connections like you said.

**Comment by jhvdb87** [comment]
The plist file of the quick start app has been updated, so that should fix your problem :).
Is in the 1.11 release
