### ISSUE TITLE
Log filled with Hue messages

### ISSUE THREAD

**Issue by cliffspencer** [PhilipsHue/PhilipsHueSDK-iOS-OSX#102]
I get a set of these

2015-09-17 15:40:17.508 LightFantastic[16424:5154335] Allocating PHHttpRequester
2015-09-17 15:40:17.509 LightFantastic[16424:5154335] Deallocating PHHttpRequest

each time the heartbeat fires, regardless of log level. Is there any way to disable these? I've tried to break on them and it doesn't look like they are being issued through Lumberjack. Please.

**Comment by bmaltais** [comment]
Same here. Would be nice to quiet them down.

**Comment by lightbow** [comment]
Amen

**Comment by cliffspencer** [comment]
Is anyone who maintains the SDK reading this list?

**Comment by samuelclay** [comment]
I would love to cleanup these log statements. It's making it very difficult to log anything else over a long period of time, as I know I'll have thousands of these "Allocating/Deallocating" statements.

**Comment by cliffspencer** [comment]
I gave up and bit the bullet. I backed down to the old SDK and undid all the changes for bridge mac vs bridge id. I just felt that I couldn't submit something that fill the entire console log.

**Comment by jhvdb87** [comment]
The allocating and deallocating messages have been removed from the latest 1.11 release.
You can also disable the logging:

[self.phHueSDK enableLogging:NO];
