### ISSUE TITLE
Failing on El Captain (No Local Connection)

### ISSUE THREAD

**Issue by ChiellieNL** [PhilipsHue/PhilipsHueSDK-iOS-OSX#104]
My app worked flawless on both Yosemite as El Captain (GM) when I was using the 1.31beta version of HueSDK.

Now I've updated my app to use 1.8beta and since that moment I'm not able to connect to the bridge anymore on El Captain (Yosemite still works fine).
When searching for bridges, it finds my bridge and displays the correct MAC and IP. When trying to connect, it doesn't come up with the pushlink notification anymore, but instead will always call the "No Local Connection" error.

Since El Captain will be released next week, is someone familiar with this and has a solution for it?

**Comment by bmaltais** [comment]
Hi, easy fix. Have a read of http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

Apply the "But What If I Don’t Know All the Insecure Domains I Need to Use?" changes ;-)

Bernard

**Comment by ChiellieNL** [comment]
Yeah.. just installed xcode on my El Captain to debug and noticed the log statement..
Thanks for the help!
