### ISSUE TITLE
Thousands of build warnings using 1.11 beta framework

### ISSUE THREAD

**Issue by lightbow** [PhilipsHue/PhilipsHueSDK-iOS-OSX#106]
I'm getting zillions of build warnings of the form:

`while processing /<path to my development folder>/HueSDK_iOS.framework/HueSDK_iOS(PHSceneSerializer1.o):
warning: /var/folders/4n/nc0bj44x7bqgnmc55x36n66h0000gn/C/org.llvm.clang.310049919/ModuleCache/20MZ5I08L0X3G/Foundation-K7W1BMS6PHG4.pcm: No such file or directory`

or

`while processing /<path to my development folder>/HueSDK_iOS.framework/HueSDK_iOS(PHHeartbeatProcessingPortal.o):
warning: Could not resolve external type c:objc(cs)NSObject`

or 

`while processing /<path to my development folder>/HueSDK_iOS.framework/HueSDK_iOS(PHBridgeResource.o):
warning: /var/folders/4n/nc0bj44x7bqgnmc55x36n66h0000gn/C/org.llvm.clang.310049919/ModuleCache/20MZ5I08L0X3G/ObjectiveC-JRA7UFEC52Z6.pcm: No object file for requested architecture`

I'm pretty sure this will cause problems with the resulting dSYM file (and could prevent apps from being accepted into the App Store... anyone try a submission with the latest framework yet?)

I've tried nuking my DerivedData folder and doing a clean build, but no luck.

**Comment by jhvdb87** [comment]
This is quite concerning indeed. I will investigate why these warnings appear. They don't show up when I am compiling the quick start app, for example, locally.

**Comment by lightbow** [comment]
Which version of Xcode are you using? Do you have bitcode turned on? (required for tvOS apps, and presumably more in the future) What's your deployment target set to?

**Comment by jhvdb87** [comment]
The compilation has been done with xcode 7 and it's compiled with bit code support yes.
I found a related issue on the apple forum:
https://forums.developer.apple.com/thread/17921

**Comment by bmaltais** [comment]
Same problem on my side too. What fixed it for me was to change the build setting from: Debug Information Format (DEBUG_INFORMATION_FORMAT) = DWARF with dSYM

to

Debug Information Format (DEBUG_INFORMATION_FORMAT) = DWARF

I am not sure what that will do to my debug logs sent from the app store...

**Comment by lightbow** [comment]
Turning off dSYM generation is not a real option for a shipping product. See also this issue: https://github.com/PhilipsHue/PhilipsHueSDK-iOS-OSX/issues/107

**Comment by bmaltais** [comment]
That is what I was afraid of... I hope Philips can fix this quickly.

**Comment by jhvdb87** [comment]
Both issues are currently under investigation, we're trying to solve the issue as soon as possible.

**Comment by jhvdb87** [comment]
Issue has been resolved. It was related to some project settings.

We release a new version with the fix as soon as possible.
