### ISSUE TITLE
Unable to archive build on SDK 1.11 with Bitcode support

### ISSUE THREAD

**Issue by ibuprofane** [PhilipsHue/PhilipsHueSDK-iOS-OSX#107]
I've updated my project to include the latest 1.11 Hue SDK, but the compiler is throwing an error when compiling for an Archive build with bitcode support prior to App Store submission. I've tried to create an archive build with the Quickstart app as well, and I'm seeing the same error:

ld: bitcode bundle could not be generated because '../HueSDK_iOS.framework/HueSDK_iOS(PHPortalConfig.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

The only change I made to the Quickstart App was to change the deployment target to iOS 9.1 (as the current 5.0 setting is not valid when bitcode is enabled). Compiling with bitcode works fine in both my project and the Quickstart app, it's only Archiving that's causing the issue.

Is anyone else encountering this issue?

Thanks,
Kevin

**Comment by jhvdb87** [comment]
see comment #106.
We are currently investigating on the issue.

**Comment by jhvdb87** [comment]
Issue has been found. We are using xcodebuild directly to compile all the architectures (arm & x86) into one framework. It seems the bitcode flags set in the targets are somehow ignored. When I added OTHER_CFLAGS="-fembed-bitcode" to the xcodebuild invocation directly, I was able to archive an app with the new compiled SDK.

We'll release a new version with this fix as soon as possible
