### ISSUE TITLE
PHWhiteListEntry?

### ISSUE THREAD

**Issue by ahknight** [PhilipsHue/PhilipsHueSDK-iOS-OSX#108]
Both SDKs have the line:

    #import "PHWhiteListEntry.h"

However this file is not in the repo with that name.  The file is "PHWhitelistEntry.h" (note the lower-case L).

Do test on case-sensitive filesystems as well; a fair amount of x-plat development is done on them.

**Comment by danielreiser** [comment]
It is but only in the built framework. You can find it here: HueSDK_iOS.framework/Versions/A/Headers/PHWhitelistEntry.h

**Comment by lightbow** [comment]
Amen. Help us help you, Philips! You have the best developer ecosystem out there, but we can do much more if we work together.

**Comment by jhvdb87** [comment]
Fixed in v1.11.3beta
