### ISSUE TITLE
Ability to Delete Lights (especially dead ones)

### ISSUE THREAD

**Issue by lightbow** [PhilipsHue/PhilipsHueSDK-iOS-OSX#79]
When I call:
        PHBridgeSendAPI *bridgeSendAPI = [[PHBridgeSendAPI alloc] init];
        [bridgeSendAPI removeLightWithId:identifier completionHandler:^(NSArray *errors) {
            [[LBErrorAndWarningController sharedController] reportErrors:errors];
        }];

I get this error:
    UNSUPPORTED_IN_THIS_VERSION = 80

I have several customers (and myself included) where dead bulbs (or bugs that caused a light to appear twice) are still in the light list coming from the bridge. It would be great to be able to nuke those entries without a full bridge reset.

**Comment by pverh** [comment]
As of SDK version 1.3.1beta it is possible to delete lights using the above method when you have a bridge running the 1.7 firmware or higher.
