### ISSUE TITLE
Unsupported Bridge Software version sent: 01023599

### ISSUE THREAD

**Issue by rph8** [PhilipsHue/PhilipsHueSDK-iOS-OSX#93]
I am using the latest SDK release (1.31beta (2015-03-20)) and am getting this message in the log file. Bridge-wise my bridge is on the latest update which was recently release.

Does anybody else get that error message?

**Comment by jordibruin** [comment]
Getting the same here.

`2015-09-19 19:57:29:380 HueQuickStartApp-iOS[42287:607] Looking up features for bridge with swversion:01023599 apiversion:1.7.0`

`2015-09-19 19:57:29:380 HueQuickStartApp-iOS[42287:607] Unsupported Bridge Software version sent: 01023599`

`2015-09-19 19:57:29:380 HueQuickStartApp-iOS[42287:607] Loading features for bridge...`

**Comment by jordibruin** [comment]
Updating the bridge through the official Hue app solved this for me.

**Comment by jhvdb87** [comment]
This issue has been resolved in the 1.11 release
